### ISSUE TITLE
Update of FormCollection with UniqueConstraint not possible

### ISSUE THREAD

**Issue by ralph089** [jrief/django-formset#34] opened 2023-02-17 13:36 UTC
Hello,

when I submit a EditCollectionView, where I can update the FormCollection, which has not been changed at all, the Form complains that it is invalid because of a unique constraint which is set.

```
class UpdateTermCollectionView(EditCollectionView):
    model = Term
    collection_class = TermFormCollection
    template_name = 'glossary/term_update.html'
    success_url = reverse_lazy('glossary:index')
```

```
class TermFormCollection(FormCollection):
    default_renderer = FormRenderer()
    term = TermForm()
    synonyms = SynonymCollection()
```

```
class Term(TimeStampedModel, models.Model):
    title_de = models.CharField(max_length=250, help_text="Term in German")
    title_en = models.CharField(max_length=250, help_text="Term in British English")
    source = models.CharField(max_length=20, choices=SOURCE_CHOICES)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=["title_de", "source"], name='unique_term_source'),
        ]
```

When I remove the unique constraint, it works as expected.

**Comment by gumish** [comment] 2023-03-19 09:15
I found the similar problem (branch https://github.com/jrief/django-formset/tree/issue_37).
I modified Company model:
```
class Company(models.Model):
    name = models.CharField(
        verbose_name="Company Name",
        max_length=50, unique=True
    )
    employees = models.IntegerField(
        verbose_name="Employees",
        null=True, blank=True
    )
```
then I wasn't able to change the Company - change employees value
![image](https://user-images.githubusercontent.com/7414504/226165333-852bb810-1f72-4f8d-b93b-ac399a88363c.png)

**Comment by jrief** [comment] 2023-03-20 22:35
I was able to reproduce this and fixed it in branch https://github.com/jrief/django-formset/tree/version_1

Currently only for a single company. For multiple companies on the root level, I haven't found any generic solution yet.

**Comment by gumish** [comment] 2023-03-21 06:12
And is it now mandatory to add the full_clean() function to all ModelForms?
https://github.com/jrief/django-formset/commit/61cc8d1398191b510d90ad0c6731fdb15b3e8dfd#diff-8fd7a2b557c98b7e06e93ad2a7166ed1037a9aa8b57735a17cbe4cf71cf0e8dd



po 20. 3. 2023 v 23:35 odesílatel Jacob Rief ***@***.***>
napsal:

**Comment by jrief** [comment] 2023-03-21 06:59
> And is it now mandatory to add the full_clean() function to all FormCollections?

unfortunately yes, because one must assign the real model instance to the form's instance. However, I will check, if I can find a more elegant solution, which fits both collection types, those with siblings and those with a single instance.

**Comment by jrief** [comment] 2023-03-21 09:35
I'm just refactoring the code. Currently my idea is to add an optional hook method to a form collection without siblings named `assign_instance()`. It defaults to noop. If overridden it shall assign the current instance to the sub-form controlling that object.

Form collections with siblings must behave differently. They shall implement a method `retrieve_instance(data)` which take the data dict and return the corresponding instance.

I implemented both variants. With slug `company` I use a collection binding to a single company. With slug `companies` I use a collection binding to multiple company objects. Model `Company` has its name set as unique. Please check the modified code and tell me if that's a feasible API for you.

**Comment by jwoithe** [comment] 2023-03-22 04:01
I think I encountered the same problem: a FormCollection's form which included a field with a unique constraint would fail validation because the unique field's value was supposedly already used. I solved it by overriding the view's get_form_collection() to ensure that the affected form's instance field was set to reflect the database record being edited. This way the standard uniqueness tests could function correctly by ignoring the apparent duplicate name if it was found in the database record being edited.
```
class Account(models.Model):
    account_name = models.CharField(max_length=64, unique=True)

class Address(models.Model):
    address_line_1 = models.CharField(max_length=128)
    ::
    account = models.ForeignKey('Account', on_delete=models.CASCADE, null=True)

class AddressCollection(FormCollection):
    min_siblings = 1
    max_siblings = 4
    def model_to_dict(self, account):
        ::
    def construct_instance(self, account, data):
        ::

class AccountCollection(FormCollection):
    account = AccountForm()
    addresses = AddressCollection()

class AccountCollectionView(EditCollectionView):
    model = Account
    collection_class = AccountCollection

    def get_form_collection(self):
        collection = super().get_form_collection()

        if self.extra_context['add'] is False and self.request.method != 'GET':
            if self.object is None:
                obj = self.get_object()
            else:
                obj = self.object
            collection.declared_holders['account'].instance = obj

        return collection
```
A related problem was a crash in the django-formset python code when adding a new Account because the validation methods assumed that there was always an object to act on (I can't recall if this was due to the unique constraint or not).  The view's get_object() method was overridden to make sure an object was explicitly created when an "add" operation was done:
```
    def get_object(self, queryset=None):

        if self.extra_context['add'] is False:
            ret = super().get_object(queryset)
            return ret

        if self.request.method != 'POST':
            return None
        placeholder_name = "temporary-name-" + get_random_string(length=24)
        return self.model.objects.create(account_name=placeholder_name)
```
Finally, the view's form_collection_invalid() method was overridden to dispose of the object created by get_object() in the event of an error:
```
    def form_collection_invalid(self, form_collection):
        if (self.extra_context['add'] is True):
            self.object.delete()
            self.object = None
        return super().form_collection_invalid(form_collection)
```
With all this in place, I was able to add and edit collections whose forms included fields with unique constraints. This was with django-formset 0.13.2. It may not be the most elegant solution but it seems to work for me.

**Comment by jrief** [comment] 2023-03-22 06:41
@jwoithe Please recheck with the branch https://github.com/jrief/django-formset/tree/version_1
If you look at the example with model `Company` you find a working solution.
This btw. has a simpler interface.

**Comment by jwoithe** [comment] 2023-03-22 07:13
Thanks. I will try to do this as soon as possible, but it won't be in the next few days. I currently have some tasks on the django project which need to be demonstrated soon and therefore don't have time right now to learn a new way to make this work. I will take a look at the new example once I work out where it is.  When time allows I will try to determine how the revised examples fit in with the structures I'm working with (I found this quite a challenge the first time around).  All that said, simpler is definitely better so I'm looking forward to checking the new code out when the opportunity arises.

**Comment by jrief** [comment] 2023-10-19 15:58
@jwoithe @ralph089 have you been able to test with the latest version?

I'd like to close this issue.

**Comment by ralph089** [comment] 2023-10-20 19:18
Yes, it‘s working! Thank you!

**Closed** 2023-10-21 21:19 UTC
