### ISSUE TITLE
Tom Select already initialized on this element

### ISSUE THREAD

**Issue by gumish** [jrief/django-formset#38] opened 2023-03-14 19:01 UTC
Hello, I've found an error with the Selectize/Tom-select  widget.
When I move **child form with Selectize widget** in a sortable FormCollection I get errors:
**Tom Select already initialized on this element**
![image](https://user-images.githubusercontent.com/7414504/225108316-52b00841-12b9-4af0-96f5-6284250f8f2b.png)

I've already tried it here https://django-formset.fly.dev/bootstrap/sortablecontact where I added Selectize widget to label (https://github.com/jrief/django-formset/blob/4b95368f3175d3034ec5e43d72ad55cdec417feb/testapp/forms/contact.py#L81)
```
    label = fields.ChoiceField(
        label="Label",
        choices=[
            ('home', "Home"),
            ('work', "Work"),
            ('mobile', "Mobile"),
            ('other', "Other"),
        widget=Selectize,
        ],
    )
```
and it also didn't work without errror.

**Comment by jrief** [comment] 2023-03-15 08:37
Could you please retry using this branch:
https://github.com/jrief/django-formset/tree/datepicker/client
There I check for already initialized modules.

An alternative is to run `npm run esbuild.monolith` and use `<script type="module" src="{% static 'formset/js/django-formset.monolith.js' %}"></script>` instead, but this is – as its name suggests – a much bigger JS file.

Remember to build the client as described here: https://django-formset.readthedocs.io/en/latest/development.html

**Comment by gumish** [comment] 2023-03-15 19:46
I've just tried both approaches:
- branch "datepicker"
- django-formset.monolith.js
but the error (when I move with form with Selectize) still remains:
![image](https://user-images.githubusercontent.com/7414504/225424870-7d66da78-610d-412e-9765-833633afa655.png)

**Comment by jrief** [comment] 2023-03-15 23:20
I couldn't reproduce this problem locally in my environment. I'll dig into that problem deeper, though.

**Comment by jrief** [comment] 2023-03-16 09:39
Please test again with HEAD on main.
Should be fixed now. As soon as it works for you, I'll release version 0.13.4

**Comment by gumish** [comment] 2023-03-16 17:21
Yeah, sorry I have almost no experience with GitHub issuing.

**Closed as completed** 2023-03-16 17:20 UTC
